name: Ask for help
description: Ask an Concierge team member for help
title: "[Ask for Help]: Summary of customer issue"
labels:
  - concierge
  - daily
  - task
body:
  - type: markdown
    attributes:
      value: "## Customer Details"
  - type: markdown
    attributes:
      value: "*Note*: All requested information must be completed before submitting the GH issue for review."
  - type: input
    id: email
    attributes:
      label: Affected Primary Email Address
      description: The affected user's primary email address
      placeholder: ex. hermione@hogwarts.com
    validations:
      required: true
  - type: input
    id: chatLink
    attributes:
      label: Concierge Chat
      description: The URL of the chat you're asking for help on
      placeholder: https://www.expensify.com/concierge/#/chat/12345678
    validations:
      required: true
  - type: textarea
    id: policyIDs
    attributes:
      label: Affected Policy IDs
      description: List policies that are affected
      placeholder: B6013AA349A14280, 11FB084582FBA666
    validations:
      required: false
  - type: textarea
    id: reportIDs
    attributes:
      label: Affected Report IDs
      description: List reports that are affected
      placeholder: R006SYJiYFVh, R00ITXLlejHg
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Outline the Problem
  - type: textarea
    id: tryingtoDo
    attributes:
      label: What is the customer trying to do?
      description: Please describe what the customer is trying to do here.
      placeholder: The customer is trying to export reports to NetSuite manually.
    validations:
      required: true
  - type: textarea
    id: expectedOutcome
    attributes:
      label: What is the expected outcome?
      description: Please provide what the expected result is here.
      placeholder: When the connection is set to create employees upon export, or when
        an employee is correctly setup with a matching email address on the
        NetSuite employee record, the report should export without errors.
    validations:
      required: true
  - type: textarea
    id: actualOutcome
    attributes:
      label: What is the actual outcome?
      description: Explain in a few sentences what happens when the customer tries to
        achieve that action.
      placeholder: "Every time they try, the receive the error: ExpensiError NS0056,
        Error creating employee: You do not have permissions to set a value for
        element entityid"
    validations:
      required: true
  - type: textarea
    id: errorMessage
    attributes:
      label: Do they see an error message?
      description: Please provide screenshots of any error messages here.
      placeholder: When the connection is set to create employees upon export, or when
        an employee is correctly setup with a matching email address on the
        NetSuite employee record, the report should export without errors.
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where is this issue occurring - web or mobile?
      options:
        - Web Chrome
        - Web Firefox
        - Web Edge
        - Web Safari
        - Mobile Android
        - Mobile iOS
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, include a link to a [relevant
        LogSearch](https://stackoverflowteams.com/c/expensify/questions/4856)
        here.
      render: shell
    validations:
      required: true
  - type: textarea
    id: additionalNotes
    attributes:
      label: Additional Notes
      description: Please provide any extra context that will be helpful to the team
        investigating this here.
      placeholder: The customer is exporting to NetSuite as Vendor Bills for
        reimbursable transactions, but Expense Reports for non-reimbursable and
        this report contains both.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Research"
  - type: markdown
    attributes:
      value:"Please link to the relevant issues/resources you reviewed while researching the customer issue."
- type: textarea
    id: githubCustomer
    attributes:
      label: Customer GitHub Issues
      description: Link any GHs that were created previously for this user and/or
        domain. Are there any existing issues related to what the customer is
        experiencing? If an open, duplicate issue exists, please add to that
        issue.
      placeholder: https://github.com/Expensify/Expensify/issues/265091
    validations:
      required: false
  - type: input
    id: zingtree
    attributes:
      label: ZingTree
      description: Insert the node-link here.
      placeholder: https://zingtree.com/host.php?tree_id=113537224&start_node=150
    validations:
      required: false
  - type: input
    id: stackoverflow
    attributes:
      label: StackOverflow
      description: Post any relevant Stack Overflow links here.
      placeholder: https://stackoverflowteams.com/c/expensify/questions/10574
    validations:
      required: false
  - type: textarea
    id: otherLinks
    attributes:
      label: "Other: Slack, Google, ExpensifyHelp/Community"
      description: Post any relevant resources that you found on our external support
        platforms, Slack links or discussions etc
      placeholder: https://github.com/Expensify/Expensify/issues/265091
    validations:
      required: false
  - type: checkboxes
    id: tested
    attributes:
      label: I tried reproducing in a test account
      description: Check this box to confirm you attempted recreating the issue in a
        test account
      options:
        - label: I tried reproducing in a test account
  - type: checkboxes
    id: preSubmitCheck
    attributes:
      label: Confirm why you created this GH issue
      description: You may select more than one.
      options:
        - label: You could not find the resolution in Expensify's resources
        - label: You do not have access to the tool needed to complete this action
        - label: The customer issue is a bug report
        - label: Other (please describe below)
  - type: textarea
    id: otherDescription
    attributes:
      label: Other
      description: Why you created this GH issue (other)
    validations:
      required: false
  - type: checkboxes
    id: sufficientCheck
    attributes:
      label: Is this GitHub sufficient?
      description: "Please review the
        [StackOverflow](https://stackoverflowteams.com/c/expensify/questions/15\
        675) on our best practices and confirm your GitHub meets the following
        expectations:"
      options:
        - label: "**Information in the GitHub** - All necessary/relevant information is
            included in the GH. The reviewer (Concierge Team member) does not
            need to reference the chat to gather additional information to
            resolve the customer issue."
        - label: "**Outlining the problem** - You have outlined the problem and provided
            all of the relevant information to solve it. You answered all of the
            questions under 'Outline the Problem.'"
        - label: "**Evidence of research** - You linked all relevant resources, Slack
            convos, GHs, StackOverflows, ZingTree Nodes, and Community articles,
            but based on the complexity of the customer issue, the GH still
            needed to be created."
        - label: "**Completing the conversation before/after asking for help** - You've
            answered all of the customer's questions (not related to the
            customer issue outlined in the GH)"
