name: Business Bank Account Review Template
description: VBBA Compliance Review Checklist
title: "Business Bank Account Review for [insert requestor's email]"
labels:
  - Daily
  - Task
body:
  - type: markdown
    attributes:
      value: "## Customer Details"
  - type: markdown
    attributes:
      value: "*Note*: All requested information must be completed before submitting
        the GH issue for review. Once complete, add the `Concierge` label."
  - type: input
    id: email
    attributes:
      label: Affected Primary Email Address
      description: The affected user's primary email address
      placeholder: ex. hermione@hogwarts.com
    validations:
      required: true
  - type: input
    id: chatLink
    attributes:
      label: Concierge Chat
      description: The URL of the chat you're asking for help on
      placeholder: https://www.expensify.com/concierge/#/chat/12345678
    validations:
      required: true
  - type: checkboxes
    id: failedChecks
    attributes:
      label: 'What are the failed checks on the VBA?'
      description: 'Check all that apply'
      options:
        - label: 'RealSearch'
          required: false
        - label: 'Company Address'
          required: false
        - label: 'Controlling Officer ID'
          required: false
        - label: 'Beneficial Officer ID'
          required: false
        - label: 'Tax/Employer Identification Number (TINcheck)'
          required: false
        - label: 'Account Ownership (GIACT)'
          required: false
  - type: markdown
    attributes:
      value: "---"         
  - type: checkboxes
    id: checks1
    attributes:
      label: 'Step 1 - Preliminary Checks:'
      description: 'Verifying details entered match our requirements.'
      options:
        - label: 'Confirm that both the company and requestor addresses are physical addresses (not PO boxes)'
          required: true
        - label: 'Confirm the Requestor information matches the Expensify account holder'
          required: true
        - label: 'Make sure that the ID in Onfido is a US-issued ID'
          required: true
  - type: checkboxes
    id: checks2
    attributes:
      label: 'Step 2 - Review / Pass Compliance Checks'
      description: 'https://zingtree.com/tree/view.php?this_project_id=156920470'
      options:
        - label: 'RealSearch passed automatically or the customer provided an acceptable document'
          required: false
        - label: 'Company Address passed automatically or the customer provided an acceptable document'
          required: false
        - label: 'Controlling Officer ID passed automatically or the customer provided an acceptable document'
          required: false
        - label: 'Beneficial Owner ID passed automatically or the customer provided an acceptable document'
          required: false
  - type: checkboxes
    id: checks3
    attributes:
      label: 'Step 3 - Did you update any customer information in the VBA Tool?'
      description: ' Check all that apply'
      options:
        - label: 'Company Address'
          required: false
        - label: 'Requestor info'
          required: false
        - label: 'Beneficial Owner info'
          required: false
        - label: 'N/A - I did not update any information'
          required: false
  - type: checkboxes
    id: checks4
    attributes:
      label: 'Step 4 - Are there any Risk Checks that failed on the VBA that the Concierge Team member needs to review?'
      description: ' Check all that apply'
      options:
        - label: 'TINcheck'
          required: false
        - label: 'GIACT'
          required: false
        - label: 'Onfido'
          required: false
        - label: 'No, only Compliance Checks failed'
          required: false
