name: Concierge Customer Escalation
about: Used by SecondResponders to create an escalated issue for Concierge Management Review
labels:
  - Concierge
  - Daily
  - Task
title: '[customer domain][brief explanation of issue]'

research_checklist:
  - item: Concierge Chat
    link: [link]
    completed: false
  - item: Customer affected
    link: [customer email]
    completed: false
  - item: Searched GitHub for customer email in existing issues
    link: [if an OPEN duplicate exists, please add to that issue and do not continue creating this one. If a CLOSED issue exists, continue creating this issue and paste that link here]
    completed: false
  - item: Searched GitHub for issue customer is experiencing
    link: [if an OPEN duplicate exists, please add to that issue and do not continue creating this one. If a CLOSED issue exists, continue creating this issue and paste that link here]
    completed: false
  - item: Admin email
    link: [any relevant domain or policy admin emails]
    completed: false
  - item: Policy IDs
    link: [all affected policy IDs]
    completed: false
  - item: Report IDs
    link: [all affected report IDs]
    completed: false
  - item: Searched ZingTree
    link: [insert node link here]
    completed: false
  - item: Supportaled into customers account and took relevant screenshots
    link: [Include where relevant in the write up below]
    completed: false
  - item: Searched Slack for customer domain and email address
    link: [insert any links here]
    completed: false
  - item: Searched Slack for issue customer is experiencing
    link: [insert any links here]
    completed: false
  - item: Tried to reproduce in a test account
    link: [If no, why not]
    completed: false

customer_action: ''
what_happens: ''
additional_notes: ''
